- .github/workflows/sphinx-doc.yml
This action is equivalent to the documentation Jenkins job the project used to have. It does the following:
* Generates the YARD documentation
* Converts the `CHANGELOG.md` to Sphinx.
* Generates the Sphinx documentation.
* Uploads the artifact
* Deploys the artifact to Github pages.
It only does this once changes are merged to master, just like the Jenkins job did.
> [ELITERT-1198] Add action to generate the Sphinx doc

- .github/workflows/ruby-linters.yml
- .rubocop.yml
- Gemfile
The action runs Rubocop and Reek on Pull Requests.
* The action doesn't fail when there are linter warnings it only adds comments to the files in the Pull Request.
* To reduce the time needed to install gems the gems needed for linting are being moved to a group and the `BUNDLE_ONLY` environment variable is being used to install only those.
* To prevent Rubocop from scanning the `vendor` directory an exclusion entry is being added to its configuration file.
> [ELITERT-1198] Add action to run Ruby linters

- documentation/source/appendix/links_and_resources.rst
Updates the links to the build infrastructure in the documentation to make them point to the corresponding Github Actions instead of the old internal Jenkins Jobs.
> [ELITERT-1198] Update doc's build infra links

- .github/workflows/sphinx-doc.yml
- documentation/source/appendix/links_and_resources.rst
* Changes the documentation generation action to include the generation of the following reports:
- Test Results Report (generated by RSpec)
- Code Coverage (generated by SimpleCOV)
- Static Code Analysis (generated by Rubocop)
* Changes the links in the "Links and Resources" page of the documentation to make them point to the generated assets instead of the internal Jenkins locations.
> [ELITERT-1198] Generate reports alongside documentation

- .github/workflows/release.yml
- dragnet.gemspec
Performs the following actions to allow the gem to be deployed to rubygems.org on release:
* Changes the `.gemspec` file to allow the gem to be pushed to rubygems.org
* Adds a Github action to build the gem, create a release and deploy the gem to rubygems.org when release pull requests are merged.
NOTE: Because this actions creates releases and pushes things to rubygems.org I could not test this on this repository. Instead I [created a personal repository](https://github.com/sergio-bobillier/sb-test) and [tested it there](https://github.com/sergio-bobillier/sb-test/actions).
> [ELITERT-1198] Set-up rubygems.org deployment

- documentation/source/user_guidelines/introduction.rst
Since the gem is now available on rubygems.org the URL of the internal gemserver is no longer required for installation, hence it is being removed from the documentation.
> [ELITERT-1198] Remove internal gemserver URL

- .github/workflows/ruby-tests.yml
The idea is to make sure that the gem works properly in both Ruby 2.x and 3.x before completely dropping the support for Ruby 2.x.
> [ELITERT-1212] Add Ruby 3.x to the RSpec verifier

- spec/dragnet/cli/master_spec.rb
- spec/dragnet/explorer_spec.rb
- spec/dragnet/exporter_spec.rb
- spec/dragnet/exporters/html_exporter_spec.rb
- spec/dragnet/exporters/id_generator_spec.rb
- spec/dragnet/exporters/json_exporter_spec.rb
- spec/dragnet/exporters/serializers/test_record_serializer_spec.rb
- spec/dragnet/repo_spec.rb
- spec/dragnet/test_record_spec.rb
- spec/dragnet/validator_spec.rb
- spec/dragnet/validators/data_validator_spec.rb
- spec/dragnet/validators/entities/repo_validator_spec.rb
- spec/dragnet/validators/entities/test_record_validator_spec.rb
- spec/dragnet/validators/fields/id_validator_spec.rb
- spec/dragnet/validators/fields/meta_data_field_validator_spec.rb
- spec/dragnet/validators/fields/repos_validator_spec.rb
- spec/dragnet/validators/fields/result_validator_spec.rb
- spec/dragnet/validators/fields/sha1_validator_spec.rb
- spec/dragnet/validators/files_validator_spec.rb
- spec/dragnet/validators/repos_validator_spec.rb
- spec/dragnet/verification_result_spec.rb
- spec/dragnet/verifier_spec.rb
- spec/dragnet/verifiers/changes_verifier_spec.rb
- spec/dragnet/verifiers/files_verifier_spec.rb
- spec/dragnet/verifiers/repos_verifier_spec.rb
- spec/dragnet/verifiers/result_verifier_spec.rb
- spec/dragnet/verifiers/test_record_verifier_spec.rb
- spec/integration/dragnet/cli/master_spec.rb
- spec/integration/dragnet/exporters/html_exporter_spec.rb
- spec/integration/dragnet/exporters/json_exporter_spec.rb
Requirement IDs were updated in #10 (8bd2af0), however their links in the spec files were left unchanged. This commit fixes that issue.
> [ELITERT-1205] Fix requirements linking in tests

- CHANGELOG.md
- lib/dragnet/exporters/templates/template.html.erb
- req/exporter.dim
- spec/integration/dragnet/exporters/html_exporter_spec.rb
This pull request adds the necessary code to allow the MTRs' descriptions to be rendered as Markdown in the generated HTML report. This enhances the readability of the text, even in simple MTRs and it allows more advanced formatting, like bullets, code blocks or even links to be added to the MTRs.
Here is a showcase of what this change does:
> [ELITERT-1221] Render MTRs' descriptions as Markdown in the generated HTML report

- documentation/source/appendix/glossary.rst
- documentation/source/introduction/contributing.rst
- documentation/source/requirements/index.rst
dim's documentation is now on Github. This commit fixes the links so that they point to the new URL, which, unlike the old one, is accessible to anyone.
> Fix links to dim's documentation

- CHANGELOG.md
- lib/dragnet/exporters/serializers/test_record_serializer.rb
- req/exporter.dim
- spec/dragnet/exporters/serializers/test_record_serializer_spec.rb
- spec/integration/dragnet/exporters/json_exporter_spec.rb
This pull request adds the necessary code to include the MTRs' file names in the JSON export.
The main driver behind this change is the need to quickly find out the source of a manual test result that has been pushed to Elasticsearch, since the ID of the MTRs not necessarily have to match the name of files that contain them.
> [ELITERT-1043] Add the MTRs' file names to the JSON export

- CHANGELOG.md
- lib/dragnet/repository.rb
- spec/dragnet/repository_spec.rb
Fixes an issue that caused Dragnet to crash when generating an HTML report for the results of an execution over a repository hosted on Github.
The reason for the crash was that Ruby's URI parser is incapable of parsing a GitHub URL, so, it was replaced by Git's `URL.parse` method, which is capable of doing it.
> [ELITERT-1221] Fix crashes with GitHub hosted repos

- CHANGELOG.md
- lib/dragnet/version.rb
- Dragnet no longer crashes when generating an HTML report for a repository
hosted on Github.
> [RELEASE] Version 5.3.1

- .github/workflows/sphinx-doc.yml
- Gemfile
Updates the Github action that generates the Sphinx documentation to also include a step to export the requirements as RST.
For this the `dim_to_rst` gem is being added to the development dependencies.
> [ELITERT-1219] Export requirements with the docs

- CHANGELOG.md
- lib/dragnet/cli/master.rb
- spec/dragnet/cli/master_spec.rb
- spec/integration/dragnet/cli/master_spec.rb
- spec/shared/cli_master.rb
Adds a `--number-only` / `-n` switch to the `--version` CLI command that only prints the version number.
The main driver behind this change is to being able to collect the tool's version during execution. The output produced when the switch is active can be used directly without further parsing.
> [ESRTEST-20396] Add --number-only to --version

- CHANGELOG.md
- lib/dragnet/version.rb
In this release:
- A `--number-only` / `-n` switch to the `--version` CLI command that only
prints the version number.
> [RELEASE] Version 5.4.0

- CHANGELOG.md
- lib/dragnet/verifiers/repos_verifier.rb
- spec/dragnet/verifiers/repos_verifier_spec.rb
Fixes a crash that occurred in multi-repo mode when all the repos listed in an MTR pass all the verifiers.
In this case the array of `Repo` objects was being returned by `ReposVerifier#verify`. This return value was bubbling up all the way up to `Verifier#verify_mtr`, which caused a `NoMethodError` to be raised because the method was expecting a `VerificationResult` object, not the array of `Repo` objects.
> [BUGFIX] Fix a crash when all the inner verifiers in a ReposVerifier pass

- CHANGELOG.md
- lib/dragnet/version.rb
In this release:
- A bug that caused Dragnet to crash during a multi-repo mode verification in
which all the repositories listed in the MTR passed the verification.
> [RELEASE] Version 5.4.1

- CHANGELOG.md
- lib/dragnet/version.rb
In this release:
- Dragnet no longer crashes when an invalid / non-existing SHA1 is used in a MTR.
> [RELEASE] Version 5.4.2

- lib/dragnet/exporters/templates/template.html.erb
The given alert covers a specific use case and is not relevant when using
Dragnet as a tool in general.
> Remove alert from HTML report
